# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
  gem "jekyll-include-cache"
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-data'
end
